[package]
name = "script_harness"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
shadow_scale_godot = { path = "../../clients/godot_thin_client/native" }
