[workspace]
members = [
    "core_sim",
    "sim_schema",
    "sim_runtime",
    "integration_tests",
    "shadow_scale_flatbuffers",
    "clients/godot_thin_client/native",
    "xtask"
]

resolver = "2"
