[tasks.setup]
description = "Install toolchain prerequisites"
command = "cargo"
args = ["fetch"]
workspace = false

[tasks.run]
description = "Run the headless simulation (placeholder)"
command = "cargo"
args = ["test", "--workspace"]
workspace = false

[tasks.cli]
description = "Run the CLI inspector"
command = "cargo"
args = ["run", "-p", "cli_inspector"]
workspace = false

[tasks.fmt]
command = "cargo"
args = ["fmt"]
workspace = false

[tasks.check]
command = "cargo"
args = ["check", "--workspace"]
workspace = false
