//! ⛔ **THE BENCH READS ZERO WHERE ZERO IS CORRECT, AND NON-ZERO WHERE IT IS NOT.**
//!
//! `sim_ai bench` (`docs/plan_ai_driver.md` §8) starts a server per seed, seats one `sim_ai` per
//! `--seats`, and computes every measure of §8.2 from the two logs each seat wrote. Nothing
//! in-process can prove that — the harness drives the **built** server and the **built** `sim_ai`
//! over the real sockets — so this test runs the built bench three times on one seed:
//!
//! 1. all-Pass, twice: **every measure is identical** between the two runs. The bench is exact on a
//!    replay of the same configuration (§8.3), so a change in the numbers is a change in the AI,
//!    never noise — and `--compare` between the two reads all-zero.
//! 2. Scripted-vs-Pass: the scripted seat's `specialist.scripted.accepted` is non-zero, and at
//!    least one scoreboard measure at the last tick differs from the same seat under Pass — the
//!    issue's bar, "acts instead of passing", as a number.
//!
//! 3. Utility-vs-Pass, over a span of **more than one liveness window**: the utility seat's `Food`
//!    specialist is live (accepted > 0 in every window — which says nothing over a one-window span,
//!    hence [`UTILITY_TURNS`]), and nothing it sent was refused — neither by the seat gate
//!    (`command.rejected` in the server log) nor by the sim (`commands_failed_total`, the feed's
//!    `… failed` rows). A proposal the server refuses is a bug in the specialist's command
//!    construction, and this is where it shows.
//!
//! **Why it lives in `core_sim/tests/`.** The bench needs the built `server`, and
//! `CARGO_BIN_EXE_server` is only defined for the package owning that bin; `sim_ai` is resolved as
//! its sibling (`common::ai_process`). The 30-turn baselines in `sim_ai/bench/baselines.json` are
//! generated by `--write-baselines`, not by this test — the bench tier is on demand (§8.3 tiers).

mod common;

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use common::ai_process::{server_binary, sim_ai_binary, Scratch};

/// Fixed and non-zero: `seed == 0` asks the server to randomise.
const MAP_SEED: &str = "11";
/// Six turns: enough for the scripted split to land and its effect to be captured, seconds in all.
const TURNS: u64 = 6;
/// **The liveness window**, restated from `LIVENESS_WINDOW_TURNS` in
/// `sim_ai/src/bench/measures.rs`: a specialist is live when it has an accepted proposal in
/// **every** window of this many turns over the run's tick span. `sim_ai` is a binary crate, so
/// this crate cannot import the constant; its is the authority.
const LIVENESS_WINDOW_TURNS: u64 = 10;
/// ⛔ **THE UTILITY RUN MUST SPAN MORE THAN ONE LIVENESS WINDOW.** Over a span shorter than
/// [`LIVENESS_WINDOW_TURNS`] the measure cuts exactly one window, and `liveness` is then
/// arithmetically identical to `accepted > 0` — which the assertion beside it already makes, so
/// the property the test names would go untested. Two more turns than the window puts a second
/// window in the span with ticks in it, so a specialist that falls silent halfway through the run
/// fails here.
const UTILITY_TURNS: u64 = LIVENESS_WINDOW_TURNS + 2;
const RIVAL_SEAT: &str = "1";
const PASS_SEATS: [&str; 2] = ["1=pass", "2=pass"];
/// The scenario's one order (`ai_seat_scenario.rs`): a legal split at the founding floor.
const SCRIPT: &str = "# the scenario's one order\n+0: split_band {faction} {own_band:0} 4\n";
const REPORT_FILE: &str = "report.json";
/// The measure name the bench gives a specialist's accepted count (`sim_ai/src/bench/measures.rs`).
const SCRIPTED_ACCEPTED_MEASURE: &str = "specialist.scripted.accepted";
/// Measure prefixes that are not scoreboard fields: the layers other than the whole seat.
const NON_SCOREBOARD_PREFIXES: [&str; 4] = ["specialist.", "link.", "orchestrator.", "intent."];
/// The utility seat under test, and the measures the bench gives its Food specialist.
const UTILITY_SEAT_SPEC: &str = "1=utility:forager";
const FOOD_ACCEPTED_MEASURE: &str = "specialist.food.accepted";
const FOOD_LIVENESS_MEASURE: &str = "specialist.food.liveness";
/// The distinct scoreboard ticks a seat wrote — the run's span, in turns.
const TURNS_OBSERVED_MEASURE: &str = "link.turns_observed";
/// Commands the sim refused, summed over the run (`sim_ai/src/bench/measures.rs`).
const COMMANDS_FAILED_MEASURE: &str = "commands_failed_total";
/// The seat gate's refusal markers in the server log (`core_sim/src/bin/server.rs`).
const REJECTED_MARKERS: [&str; 2] = ["command.rejected", "command.split.rejected"];
const SERVER_LOG_FILE: &str = "server.log";

/// Run the built bench on [`MAP_SEED`] for `turns` with `seats`, into `out`, plus `extra` args.
fn bench(
    sim_ai: &Path,
    out: &Path,
    turns: u64,
    seats: &[String],
    extra: &[&str],
) -> serde_json::Value {
    let mut command = Command::new(sim_ai);
    command
        .arg("bench")
        .arg("--server")
        .arg(server_binary())
        .args(["--seeds", MAP_SEED, "--turns", &turns.to_string()])
        .arg("--out")
        .arg(out);
    for seat in seats {
        command.args(["--seats", seat]);
    }
    command.args(extra);
    let output = command.output().expect("the built sim_ai runs");
    assert!(
        output.status.success(),
        "sim_ai bench exited {}\n--- stdout ---\n{}\n--- stderr ---\n{}",
        output.status,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let report = fs::read_to_string(out.join(REPORT_FILE)).expect("the report was written");
    serde_json::from_str(&report).expect("the report is JSON")
}

/// The measures of `seat` on [`MAP_SEED`] in `report`.
fn seat_measures(
    report: &serde_json::Value,
    seat: &str,
) -> serde_json::Map<String, serde_json::Value> {
    report["measures"][MAP_SEED][seat]
        .as_object()
        .unwrap_or_else(|| panic!("seat {seat} has measures in the report"))
        .clone()
}

#[test]
fn the_bench_is_exact_on_a_replay_and_reads_a_scripted_seat_as_non_zero() {
    let scratch = Scratch::new("ai_bench");
    let sim_ai = sim_ai_binary();
    let pass_seats: Vec<String> = PASS_SEATS.iter().map(|seat| (*seat).to_owned()).collect();

    // 1. Pass vs Pass, twice.
    let first_dir = scratch.dir.join("pass_first");
    let second_dir = scratch.dir.join("pass_second");
    let first = bench(&sim_ai, &first_dir, TURNS, &pass_seats, &[]);
    let second = bench(
        &sim_ai,
        &second_dir,
        TURNS,
        &pass_seats,
        &["--compare", first_dir.to_str().expect("utf-8 path")],
    );
    assert_eq!(
        first["measures"], second["measures"],
        "two all-Pass runs of the same seed measured differently"
    );
    for seat in PASS_SEATS {
        let (faction, _) = seat.split_once('=').expect("a seat spec");
        let deltas = second["compare"][MAP_SEED][faction]
            .as_object()
            .expect("--compare wrote a delta per seat");
        for (measure, delta) in deltas {
            assert!(
                delta.is_null() || delta.as_f64() == Some(0.0),
                "seat {faction} {measure}: delta {delta} on an exact replay"
            );
        }
        let measures = seat_measures(&second, faction);
        assert_eq!(
            measures[TURNS_OBSERVED_MEASURE].as_f64(),
            Some(TURNS as f64),
            "seat {faction} observed every turn it played"
        );
        assert_eq!(
            measures["link.turns_lost_to_timeout"].as_f64(),
            Some(0.0),
            "seat {faction} lost no turn"
        );
        assert!(
            !measures.contains_key(SCRIPTED_ACCEPTED_MEASURE),
            "a Pass seat has no scripted specialist"
        );
    }

    // 2. Scripted vs Pass, on the same seed and seat as the control.
    let script_path: PathBuf = scratch.dir.join("scenario.script");
    fs::write(&script_path, SCRIPT).expect("the script writes");
    let scripted_dir = scratch.dir.join("scripted");
    let scripted_seats = [
        format!("{RIVAL_SEAT}=scripted:{}", script_path.display()),
        PASS_SEATS[1].to_owned(),
    ];
    let scripted = bench(&sim_ai, &scripted_dir, TURNS, &scripted_seats, &[]);
    let acted = seat_measures(&scripted, RIVAL_SEAT);
    let passed = seat_measures(&first, RIVAL_SEAT);
    assert!(
        acted[SCRIPTED_ACCEPTED_MEASURE].as_f64().unwrap_or(0.0) > 0.0,
        "the scripted seat accepted no proposal: {acted:?}"
    );
    let differing: Vec<&String> = acted
        .iter()
        .filter(|(name, _)| {
            !NON_SCOREBOARD_PREFIXES
                .iter()
                .any(|prefix| name.starts_with(prefix))
        })
        .filter(|(name, value)| passed.get(*name) != Some(value))
        .map(|(name, _)| name)
        .collect();
    assert!(
        !differing.is_empty(),
        "the scripted seat's scoreboard at the last tick is the Pass seat's, field for field: \
         acting changed nothing measurable\n{acted:?}"
    );
}

/// ⛔ **The utility brain acts, is live, and sends nothing the server refuses.**
#[test]
fn the_utility_seat_is_live_and_nothing_it_sends_is_refused() {
    let scratch = Scratch::new("ai_bench_utility");
    let sim_ai = sim_ai_binary();
    let out = scratch.dir.join("utility");
    let seats = [UTILITY_SEAT_SPEC.to_owned(), PASS_SEATS[1].to_owned()];
    let report = bench(&sim_ai, &out, UTILITY_TURNS, &seats, &[]);
    let measures = seat_measures(&report, RIVAL_SEAT);
    assert!(
        measures[FOOD_ACCEPTED_MEASURE].as_f64().unwrap_or(0.0) > 0.0,
        "the Food specialist accepted nothing: {measures:?}"
    );
    // Liveness only says more than `accepted > 0` when the span is cut into more than one window,
    // so the span is asserted first: the measure's windows are `[first, first + 10)`, `[first + 10,
    // …)`, and N consecutive observed ticks span N − 1, so N must exceed the window.
    let observed = measures[TURNS_OBSERVED_MEASURE].as_f64().unwrap_or(0.0);
    assert!(
        observed > LIVENESS_WINDOW_TURNS as f64,
        "the run spans one liveness window ({observed} turns), so `liveness` is just \
         `accepted > 0` and the property below is untested"
    );
    assert_eq!(
        measures[FOOD_LIVENESS_MEASURE].as_f64(),
        Some(1.0),
        "the Food specialist fell silent for a whole window: {measures:?}"
    );
    assert_eq!(
        measures[COMMANDS_FAILED_MEASURE].as_f64(),
        Some(0.0),
        "the sim refused a command the utility seat sent: {measures:?}"
    );
    let server_log = common::ai_process::strip_ansi(
        &fs::read_to_string(out.join(MAP_SEED).join(SERVER_LOG_FILE))
            .expect("the server log reads"),
    );
    for marker in REJECTED_MARKERS {
        assert!(
            !server_log.contains(marker),
            "the seat gate refused a command ({marker}):\n{}",
            common::ai_process::log_tail(&out.join(MAP_SEED).join(SERVER_LOG_FILE))
        );
    }
}
